### ISSUE TITLE
how about make a ray executor to deduplication

### ISSUE THREAD

**Issue by simplew2011** [huggingface/datatrove#119] opened 2024-03-08 11:37 UTC
- https://github.com/ChenghaoMou/text-dedup/blob/main/text_dedup/minhash_spark.py
- reference：https://github.com/alibaba/data-juicer/blob/main/data_juicer/core/ray_executor.py
- Ray is simpler and faster than Spark

**Comment by guipenedo** [comment] 2024-04-11 12:48
closed as duplicate of #62

**Closed by guipenedo** 2024-04-11 12:48 UTC
